### ISSUE TITLE
Check for steamapps folder is case sensitive when verifying for game directory in config.py

### ISSUE THREAD

**Issue by Stepanma01** [RaidingForPants/hd2-audio-modder#17]
Hi,
Tried using this tool myself, for some reason my "steamapps" folder is named "SteamApps" causing the following check to fail in config.py:
`and game_data_path.endswith("steamapps/common/Helldivers 2/data"):`

for comparison my directory path would end with:
`SteamApps/common/Helldivers 2/data`

I'll download the source to fix it locally on my PC, but thought I'd let you know.

**Comment by RaidingForPants** [comment]
Fixed in code, release planned for later

**Comment by RaidingForPants** [comment]
Fixed in version 1.14
