### ISSUE TITLE
Version 1.16 is detected as a virus

### ISSUE THREAD

**Issue by Kevin-Schnaubelt-Jr** [RaidingForPants/hd2-audio-modder#47]
Other versions don't have this issue, but somehow 1.16 refuses to download because my computer insists its a virus, even though it's just a zip.

**Comment by RaidingForPants** [comment]
Will look into this. Not sure why it would be happening, I didn't do anything different from previous versions

**Comment by RaidingForPants** [comment]
I rezipped the file using no compression this time and it seems to have fixed the issue. Asked a couple people to download it and Windows Defender didn't block it.
